export type Book = {
  id: string;
  title: string;
  author: string;
  price: number;
  genre: string;
  year: number;
  rating: number;
  pages: number;
  format: string;
  blurb: string;
  description: string;
  featured?: boolean;
  palette: { spine: string; face: string; ink: string };
};

const palettes = [
  { spine: "#2f4a35", face: "#3d5c42", ink: "#f3ead6" },
  { spine: "#5a3a24", face: "#744c2f", ink: "#f6e9d2" },
  { spine: "#3b4a5c", face: "#4c6076", ink: "#f1eadd" },
  { spine: "#6b4b1f", face: "#8a6428", ink: "#fbf1dc" },
  { spine: "#4b2f3c", face: "#63404f", ink: "#f5e8de" },
  { spine: "#25453f", face: "#345c53", ink: "#eff0e0" },
];

const p = (i: number) => palettes[i % palettes.length]!;

export const genres = [
  "Literary Fiction",
  "Mystery",
  "Poetry",
  "Nature Writing",
  "Fantasy",
  "History",
  "Cookbooks",
  "Children",
];

export const books: Book[] = [
  {
    id: "the-moss-cartographer",
    title: "The Moss Cartographer",
    author: "Iris Halloway",
    price: 24.0,
    genre: "Literary Fiction",
    year: 2023,
    rating: 4.8,
    pages: 342,
    format: "Hardcover",
    blurb: "A botanist maps the forest floor and, accidentally, her own grief.",
    description:
      "Told across three damp autumns in the Pacific Northwest, Iris Halloway's debut follows a field botanist who begins charting moss colonies after her sister disappears. Precise, patient, and quietly devastating, it is a novel about the things that grow in shadow.",
    featured: true,
    palette: p(0),
  },
  {
    id: "lantern-in-the-larder",
    title: "A Lantern in the Larder",
    author: "Bertie Nwosu",
    price: 19.5,
    genre: "Mystery",
    year: 2021,
    rating: 4.5,
    pages: 288,
    format: "Paperback",
    blurb: "A village cook solves a poisoning with nothing but her pantry notes.",
    description:
      "When the parish treasurer collapses at the harvest supper, cook Adaeze Bell is the only one who remembers exactly what went into every dish. A warm, wry, tightly plotted village mystery with recipes hidden in the margins.",
    featured: true,
    palette: p(1),
  },
  {
    id: "field-notes-on-longing",
    title: "Field Notes on Longing",
    author: "Mira Sandoval",
    price: 16.0,
    genre: "Poetry",
    year: 2024,
    rating: 4.9,
    pages: 96,
    format: "Paperback",
    blurb: "Fifty short poems on distance, orchards, and long-distance trains.",
    description:
      "Sandoval writes the way light moves through a greenhouse. This slim collection gathers fifty poems written between two cities, each one a small argument for staying tender.",
    featured: true,
    palette: p(2),
  },
  {
    id: "the-hedgerow-year",
    title: "The Hedgerow Year",
    author: "Thomas Ferrell",
    price: 28.0,
    genre: "Nature Writing",
    year: 2020,
    rating: 4.7,
    pages: 410,
    format: "Hardcover",
    blurb: "Twelve months walking one mile of English hedge.",
    description:
      "Ferrell walked the same mile of hedgerow every week for a year. The result is a masterclass in attention: blackthorn, wren, dormouse, frost, and the slow politics of land.",
    featured: true,
    palette: p(3),
  },
  {
    id: "salt-and-signal-fire",
    title: "Salt and Signal Fire",
    author: "Odile Marchetti",
    price: 26.5,
    genre: "Fantasy",
    year: 2022,
    rating: 4.6,
    pages: 620,
    format: "Hardcover",
    blurb: "Lighthouse keepers guard a coast where the sea remembers names.",
    description:
      "On the Vantic coast, keepers burn salt to hold back a tide that speaks. Marchetti's epic is tidal in structure — patient, then overwhelming — and builds one of the most inventive magic systems in recent fantasy.",
    featured: true,
    palette: p(4),
  },
  {
    id: "paper-lanterns-of-kyoto",
    title: "The Paper Lanterns of Kyoto",
    author: "Haruko Miyagi",
    price: 22.0,
    genre: "History",
    year: 2019,
    rating: 4.4,
    pages: 368,
    format: "Paperback",
    blurb: "Four centuries of a single lantern-making family.",
    description:
      "A meticulous, generous history of craft, told through the ledgers of one Kyoto workshop and the wars, fires, and fashions it survived.",
    palette: p(5),
  },
  {
    id: "the-quiet-kitchen",
    title: "The Quiet Kitchen",
    author: "Elena Brzozowska",
    price: 34.0,
    genre: "Cookbooks",
    year: 2023,
    rating: 4.8,
    pages: 256,
    format: "Hardcover",
    blurb: "Ninety slow suppers for one, two, or a full table.",
    description:
      "Brzozowska cooks from a small flat with two burners and infinite patience. Braises, grains, preserved lemons, and a whole chapter on what to do with bread that has gone hard.",
    featured: true,
    palette: p(1),
  },
  {
    id: "where-the-owls-count",
    title: "Where the Owls Count",
    author: "Pearl Adeyemi",
    price: 15.0,
    genre: "Children",
    year: 2024,
    rating: 4.9,
    pages: 40,
    format: "Picture Book",
    blurb: "A bedtime counting book for children who refuse to sleep.",
    description:
      "One owl, two moths, three sleepy foxes. Adeyemi's ink-and-wash illustrations glow, and the rhyme lands softly enough to end the day on.",
    palette: p(0),
  },
  {
    id: "the-glasshouse-letters",
    title: "The Glasshouse Letters",
    author: "Ruth Vanterpool",
    price: 21.0,
    genre: "Literary Fiction",
    year: 2018,
    rating: 4.3,
    pages: 314,
    format: "Paperback",
    blurb: "Two gardeners correspond for thirty years and never meet.",
    description:
      "An epistolary novel built from seed orders, weather reports, and increasingly unguarded confessions. Funny early, unbearable late, and perfect throughout.",
    palette: p(2),
  },
  {
    id: "eleven-crows-at-dusk",
    title: "Eleven Crows at Dusk",
    author: "Cormac Innes",
    price: 18.5,
    genre: "Mystery",
    year: 2022,
    rating: 4.2,
    pages: 352,
    format: "Paperback",
    blurb: "A rural detective returns to the farm he swore he'd left.",
    description:
      "Innes writes weather like a threat. A missing shepherd, a family ledger with pages torn out, and a detective who knows every wall on the hill.",
    palette: p(3),
  },
  {
    id: "root-and-branch",
    title: "Root and Branch",
    author: "Sefa Owusu",
    price: 27.0,
    genre: "Nature Writing",
    year: 2021,
    rating: 4.6,
    pages: 298,
    format: "Hardcover",
    blurb: "How city trees survive us.",
    description:
      "Part arboriculture, part memoir of a childhood spent on a housing estate with one enormous plane tree. Owusu makes canopy politics urgent and personal.",
    palette: p(5),
  },
  {
    id: "the-tessellated-crown",
    title: "The Tessellated Crown",
    author: "Nadia Ruiz-Kerr",
    price: 25.0,
    genre: "Fantasy",
    year: 2024,
    rating: 4.5,
    pages: 544,
    format: "Hardcover",
    blurb: "A mosaic-maker inherits a throne she cannot legally sit on.",
    description:
      "Court intrigue with grout under its fingernails. Ruiz-Kerr's guild politics are as sharp as her sword work, and the ending re-reads the whole book.",
    palette: p(4),
  },
  {
    id: "small-hours-large-questions",
    title: "Small Hours, Large Questions",
    author: "Yusuf Demir",
    price: 17.0,
    genre: "Poetry",
    year: 2020,
    rating: 4.4,
    pages: 112,
    format: "Paperback",
    blurb: "Insomniac poems for the 3 a.m. mind.",
    description:
      "Demir catalogues the strange clarity of the sleepless: taxis, kettles, the neighbour's radio, the fear that arrives on schedule.",
    palette: p(2),
  },
  {
    id: "bread-weather",
    title: "Bread Weather",
    author: "Margit Halvorsen",
    price: 32.0,
    genre: "Cookbooks",
    year: 2022,
    rating: 4.7,
    pages: 224,
    format: "Hardcover",
    blurb: "Baking by season, humidity, and mood.",
    description:
      "A Norwegian baker's practical, opinionated guide to reading your kitchen instead of your timer. Rye, barley, cardamom, and a lot of patience.",
    palette: p(3),
  },
  {
    id: "the-cartwright-inheritance",
    title: "The Cartwright Inheritance",
    author: "Delia Frost",
    price: 20.0,
    genre: "History",
    year: 2017,
    rating: 4.1,
    pages: 486,
    format: "Paperback",
    blurb: "One canal company and the century it rearranged.",
    description:
      "Frost traces the money: locks, lawsuits, ledgers, and the families quietly rewritten by a waterway nobody remembers building.",
    palette: p(1),
  },
  {
    id: "a-house-of-borrowed-light",
    title: "A House of Borrowed Light",
    author: "Anouk Delacroix",
    price: 23.5,
    genre: "Literary Fiction",
    year: 2025,
    rating: 4.7,
    pages: 276,
    format: "Hardcover",
    blurb: "Three sisters, one crumbling coastal hotel, one final season.",
    description:
      "Delacroix writes families the way tides write cliffs — slowly, then all at once. A luminous, argumentative, deeply funny novel about inheritance.",
    featured: true,
    palette: p(0),
  },
  {
    id: "the-fern-atlas",
    title: "The Fern Atlas",
    author: "Gregor Lindqvist",
    price: 45.0,
    genre: "Nature Writing",
    year: 2023,
    rating: 4.9,
    pages: 320,
    format: "Illustrated Hardcover",
    blurb: "Two hundred ferns, rendered in botanical plate.",
    description:
      "A reference book beautiful enough to leave open on the table. Every plate hand-painted, every entry usable in the field.",
    palette: p(5),
  },
  {
    id: "night-market-detective",
    title: "The Night Market Detective",
    author: "Lin Wei-Chen",
    price: 18.0,
    genre: "Mystery",
    year: 2024,
    rating: 4.6,
    pages: 330,
    format: "Paperback",
    blurb: "A noodle vendor who notices everything.",
    description:
      "Taipei after midnight: steam, neon, gossip, and a series of thefts that only make sense if you know who eats where.",
    palette: p(4),
  },
  {
    id: "the-boy-who-planted-libraries",
    title: "The Boy Who Planted Libraries",
    author: "Amara Kone",
    price: 16.5,
    genre: "Children",
    year: 2022,
    rating: 4.8,
    pages: 48,
    format: "Picture Book",
    blurb: "Seeds of paper, shelves of trees.",
    description:
      "A gentle fable about a boy who buries a book and grows a reading room. Warm gouache illustrations and a last page that earns its sigh.",
    palette: p(3),
  },
  {
    id: "cathedral-of-thorns",
    title: "Cathedral of Thorns",
    author: "Vesna Kovac",
    price: 29.0,
    genre: "Fantasy",
    year: 2021,
    rating: 4.4,
    pages: 588,
    format: "Hardcover",
    blurb: "The forest has taken the city back, and it is building something.",
    description:
      "Kovac's overgrown metropolis is one of fantasy's great settings: root-cracked avenues, thorn priests, and a botanist-heretic at the centre.",
    palette: p(0),
  },
  {
    id: "letters-from-the-lighthouse-keeper",
    title: "Letters from the Lighthouse Keeper",
    author: "Fergus Blaine",
    price: 19.0,
    genre: "History",
    year: 2016,
    rating: 4.3,
    pages: 262,
    format: "Paperback",
    blurb: "Forty years of logbooks from a rock in the Atlantic.",
    description:
      "Edited with a light hand, these logbooks record storms, supply boats, birds, boredom, and one extraordinary rescue.",
    palette: p(2),
  },
  {
    id: "the-slow-preserve",
    title: "The Slow Preserve",
    author: "Josefina Ferrer",
    price: 30.0,
    genre: "Cookbooks",
    year: 2025,
    rating: 4.7,
    pages: 240,
    format: "Hardcover",
    blurb: "Jams, ferments, and cures for a small pantry.",
    description:
      "Ferrer's preserving book assumes no cellar and no special equipment — only a willingness to wait. Includes a superb chapter on vinegars.",
    palette: p(1),
  },
  {
    id: "an-almanac-of-small-weather",
    title: "An Almanac of Small Weather",
    author: "Kit Ravensworth",
    price: 21.5,
    genre: "Poetry",
    year: 2019,
    rating: 4.5,
    pages: 128,
    format: "Paperback",
    blurb: "A poem for every kind of drizzle.",
    description:
      "Ravensworth's almanac moves month by month through mist, hail, heatwave, and the particular grey of a February afternoon.",
    palette: p(5),
  },
  {
    id: "the-understory",
    title: "The Understory",
    author: "Beatriz Alencar",
    price: 24.5,
    genre: "Literary Fiction",
    year: 2020,
    rating: 4.6,
    pages: 398,
    format: "Paperback",
    blurb: "A logging town, a returning daughter, a contested map.",
    description:
      "Alencar's novel of the Atlantic Forest is furious and precise, moving between a survey office and a canopy nobody in charge has ever climbed.",
    palette: p(4),
  },
];

export const findBook = (id: string) => books.find((b) => b.id === id);

export const formatPrice = (value: number) =>
  new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(value);
